apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: cpu-example
spec:
  containers:
    - name: memory-demo-ctr
      image: polinux/stress
      resources:
        limits:
          memory: "10Mi"
        requests:
          memory: "5Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "15M", "--vm-hang", "1"]
