apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-server
  labels:
    app: simple-web-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: simple-web-server
  template:
    metadata:
      labels:
        app: simple-web-server
    spec:
      containers:
        - name: simple-web-server
          image: {{AWS_URL}}/{{IMAGE_NAME}}
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-server-service
spec:
  selector:
    app: simple-web-server
  ports:
    - port: 8080
      targetPort: 8080
